// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package openapi

import (
	"time"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for GetUserPostsTimelineResponseType.
const (
	GetUserPostsTimelineResponseTypePost        GetUserPostsTimelineResponseType = "post"
	GetUserPostsTimelineResponseTypeQuoteRepost GetUserPostsTimelineResponseType = "quoteRepost"
	GetUserPostsTimelineResponseTypeRepost      GetUserPostsTimelineResponseType = "repost"
)

// BlockUserRequest defines model for block_user_request.
type BlockUserRequest struct {
	TargetUserId string `json:"target_user_id"`
}

// CreateFollowshipRequest defines model for create_followship_request.
type CreateFollowshipRequest struct {
	TargetUserID string `json:"targetUserID"`
}

// CreateFollowshipResponse defines model for create_followship_response.
type CreateFollowshipResponse struct {
	Message string `json:"message"`
}

// CreatePostRequest defines model for create_post_request.
type CreatePostRequest struct {
	Text string `json:"text"`
}

// CreatePostResponse Response when creating a timeline item.
type CreatePostResponse struct {
	AuthorId  string    `json:"authorId"`
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	Text      string    `json:"text"`
	Type      string    `json:"type"`
}

// CreateQuoteRepostRequest defines model for create_quote_repost_request.
type CreateQuoteRepostRequest struct {
	PostId string `json:"post_id"`
	Text   string `json:"text"`
}

// CreateQuoteRepostResponse Response when creating a quote repost.
type CreateQuoteRepostResponse struct {
	QuoteRepost QuoteRepost `json:"quoteRepost"`
}

// CreateRepostRequest defines model for create_repost_request.
type CreateRepostRequest struct {
	PostId string `json:"post_id"`
}

// CreateRepostResponse defines model for create_repost_response.
type CreateRepostResponse = Repost

// CreateUserRequest defines model for create_user_request.
type CreateUserRequest struct {
	DisplayName string `json:"display_name"`
	Password    string `json:"password"`
	Username    string `json:"username"`
}

// CreateUserResponse defines model for create_user_response.
type CreateUserResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// DeleteFollowshipResponse defines model for delete_followship_response.
type DeleteFollowshipResponse struct {
	Message string `json:"message"`
}

// DeleteRepostRequest defines model for delete_repost_request.
type DeleteRepostRequest struct {
	RepostId string `json:"repost_id"`
}

// DeleteUserByIdResponse defines model for delete_user_by_id_response.
type DeleteUserByIdResponse struct {
	Message string `json:"message"`
}

// FindUserByIdResponse defines model for find_user_by_id_response.
type FindUserByIdResponse struct {
	Bio         string    `json:"bio"`
	CreatedAt   time.Time `json:"created_at"`
	DisplayName string    `json:"display_name"`
	Id          string    `json:"id"`
	IsPrivate   bool      `json:"is_private"`
	UpdatedAt   time.Time `json:"updated_at"`
	Username    string    `json:"username"`
}

// GetReverseChronologicalHomeTimelineResponse defines model for get_reverse_chronological_home_timeline_response.
type GetReverseChronologicalHomeTimelineResponse struct {
	Data *struct {
		EventType     string `json:"event_type"`
		TimelineItems struct {
			AuthorId     string    `json:"authorId"`
			CreatedAt    time.Time `json:"createdAt"`
			Id           string    `json:"id"`
			ParentPostId *struct {
				UUID  string `json:"UUID"`
				Valid bool   `json:"Valid"`
			} `json:"parentPostId,omitempty"`
			Text *string `json:"text,omitempty"`
			Type string  `json:"type"`
		} `json:"timeline_items"`
	} `json:"data,omitempty"`
}

// GetUserPostsTimelineResponse Response when fetching timeline items.
type GetUserPostsTimelineResponse = []struct {
	AuthorId     string    `json:"authorId"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	ParentPostId *struct {
		UUID  string `json:"UUID"`
		Valid bool   `json:"Valid"`
	} `json:"parentPostId,omitempty"`
	Text string                           `json:"text"`
	Type GetUserPostsTimelineResponseType `json:"type"`
}

// GetUserPostsTimelineResponseType defines model for GetUserPostsTimelineResponse.Type.
type GetUserPostsTimelineResponseType string

// LikePostRequest defines model for like_post_request.
type LikePostRequest struct {
	PostId string `json:"post_id"`
}

// LoginRequest defines model for login_request.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for login_response.
type LoginResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// MuteUserRequest defines model for mute_user_request.
type MuteUserRequest struct {
	TargetUserId string `json:"target_user_id"`
}

// QuoteRepost defines model for quote_repost.
type QuoteRepost struct {
	AuthorId     string    `json:"authorId"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	ParentPostId struct {
		UUID  string `json:"UUID"`
		Valid bool   `json:"Valid"`
	} `json:"parentPostId"`
	Text string `json:"text"`
	Type string `json:"type"`
}

// Repost defines model for repost.
type Repost struct {
	AuthorId     string    `json:"authorId"`
	CreatedAt    time.Time `json:"createdAt"`
	Id           string    `json:"id"`
	ParentPostId struct {
		UUID  string `json:"UUID"`
		Valid bool   `json:"Valid"`
	} `json:"parentPostId"`
	Type string `json:"type"`
}

// User defines model for user.
type User struct {
	Bio         string    `json:"bio"`
	CreatedAt   time.Time `json:"createdAt"`
	DisplayName string    `json:"displayName"`
	Id          string    `json:"id"`
	IsPrivate   bool      `json:"isPrivate"`
	UpdatedAt   time.Time `json:"updatedAt"`
	Username    string    `json:"username"`
}

// VerifySessionResponse defines model for verify_session_response.
type VerifySessionResponse struct {
	User User `json:"user"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = CreateUserRequest

// CreateFollowshipJSONRequestBody defines body for CreateFollowship for application/json ContentType.
type CreateFollowshipJSONRequestBody = CreateFollowshipRequest

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = CreatePostRequest

// CreateQuoteRepostJSONRequestBody defines body for CreateQuoteRepost for application/json ContentType.
type CreateQuoteRepostJSONRequestBody = CreateQuoteRepostRequest

// BlockUserJSONRequestBody defines body for BlockUser for application/json ContentType.
type BlockUserJSONRequestBody = BlockUserRequest

// LikePostJSONRequestBody defines body for LikePost for application/json ContentType.
type LikePostJSONRequestBody = LikePostRequest

// MuteUserJSONRequestBody defines body for MuteUser for application/json ContentType.
type MuteUserJSONRequestBody = MuteUserRequest

// CreateRepostJSONRequestBody defines body for CreateRepost for application/json ContentType.
type CreateRepostJSONRequestBody = CreateRepostRequest

// DeleteRepostJSONRequestBody defines body for DeleteRepost for application/json ContentType.
type DeleteRepostJSONRequestBody = DeleteRepostRequest
