apiVersion: v1
data:
  ENV_VALUE01: ENV_VALUEgit
kind: ConfigMap
metadata:
  name: blue-greeen-sample-config-d2c6kg5hmf
  namespace: default
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: rollout-blue-green
  name: argocd-config
  namespace: default
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: kustomize/overlays/stg
    repoURL: https://github.com/okuda-seminar/Twitter-Clone.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
