swagger: "2.0"
info:
    title: Tweets Service
    description: Service for managing tweets
    version: 0.0.1
host: 0.0.0.0:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/tweets:
        post:
            tags:
                - tweets
            summary: CreateTweet tweets
            operationId: tweets#CreateTweet
            parameters:
                - name: CreateTweetRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TweetsCreateTweetRequestBody'
                    required:
                        - user_id
                        - text
            responses:
                "200":
                    description: Created tweet
                    schema:
                        $ref: '#/definitions/TweetsCreateTweetResponseBody'
                        required:
                            - id
                            - user_id
                            - text
                            - created_at
                "400":
                    description: Failed to create tweet
                    schema:
                        $ref: '#/definitions/TweetsCreateTweetBadRequestResponseBody'
                "404":
                    description: User was not found
                    schema:
                        $ref: '#/definitions/TweetsCreateTweetNotFoundResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - tweets
            summary: Download ./gen/http/openapi.json
            operationId: tweets#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    TweetsCreateTweetBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CreateTweet_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsCreateTweetNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: CreateTweet_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TweetsCreateTweetRequestBody:
        title: TweetsCreateTweetRequestBody
        type: object
        properties:
            text:
                type: string
                example: Sit dolorem.
            user_id:
                type: integer
                example: 7490648830196259010
                format: int64
        example:
            text: Consequuntur perferendis et.
            user_id: 5060174367728385028
        required:
            - user_id
            - text
    TweetsCreateTweetResponseBody:
        title: TweetsCreateTweetResponseBody
        type: object
        properties:
            created_at:
                type: string
                example: "1981-08-21T11:06:41Z"
                format: date-time
            id:
                type: integer
                example: 3478854592352156500
                format: int64
            text:
                type: string
                example: Voluptatem et amet.
            user_id:
                type: integer
                example: 966348111099881345
                format: int64
        example:
            created_at: "1989-09-02T14:39:09Z"
            id: 5632408719802807624
            text: Consequatur ea.
            user_id: 3046415697951589746
        required:
            - id
            - user_id
            - text
            - created_at
