openapi: 3.0.3
info:
    title: Tweets Service
    description: Service for managing tweets
    version: 0.0.1
servers:
    - url: http://0.0.0.0:80/api/tweets
paths:
    /api/tweets:
        delete:
            tags:
                - tweets
            summary: DeleteTweet tweets
            operationId: tweets#DeleteTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteTweetRequestBody'
                        example:
                            id: Officiis explicabo id omnis dolores et ipsa.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: CreateTweet tweets
            operationId: tweets#CreateTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateTweetRequestBody'
                        example:
                            text: Sunt sed quisquam ad corrupti labore consequatur.
                            user_id: Voluptas omnis nesciunt incidunt et totam eos.
            responses:
                "200":
                    description: Created tweet
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Tweet'
                            example:
                                created_at: "1981-08-21T11:06:41Z"
                                id: Quis est facere quisquam commodi totam sint.
                                text: Voluptatem et amet.
                                user_id: Et id adipisci.
                "400":
                    description: 'BadRequest: Failed to create tweet'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: User was not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/tweets/like:
        delete:
            tags:
                - tweets
            summary: DeleteTweetLike tweets
            operationId: tweets#DeleteTweetLike
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: Nemo rerum fugit voluptate harum facilis cum.
                            user_id: Quod cumque iusto deleniti doloremque.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: LikeTweet tweets
            operationId: tweets#LikeTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: Iste quo et assumenda enim ut.
                            user_id: Voluptatem ab nihil dolor perspiciatis.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - tweets
            summary: Download ./gen/http/openapi.json
            operationId: tweets#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreateTweetRequestBody:
            type: object
            properties:
                text:
                    type: string
                    example: Commodi possimus qui eligendi.
                user_id:
                    type: string
                    example: Ipsa iusto quasi dolor est unde.
            example:
                text: Architecto repellendus.
                user_id: Quae reiciendis sed nobis aperiam.
            required:
                - user_id
                - text
        DeleteTweetRequestBody:
            type: object
            properties:
                id:
                    type: string
                    example: Explicabo eius est illo.
            example:
                id: Sit repellat minima.
            required:
                - id
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        LikeTweetRequestBody:
            type: object
            properties:
                tweet_id:
                    type: string
                    example: Blanditiis quaerat commodi natus.
                user_id:
                    type: string
                    example: Aperiam perferendis laboriosam aspernatur.
            example:
                tweet_id: Et tenetur.
                user_id: Quidem qui voluptatem.
            required:
                - tweet_id
                - user_id
        Tweet:
            type: object
            properties:
                created_at:
                    type: string
                    example: "1976-12-09T13:35:38Z"
                    format: date-time
                id:
                    type: string
                    example: Expedita quis enim.
                text:
                    type: string
                    example: Vero commodi illo praesentium sunt.
                user_id:
                    type: string
                    example: Quia autem pariatur voluptatem.
            example:
                created_at: "1999-09-29T19:04:00Z"
                id: Qui velit eum.
                text: Mollitia quod sunt maiores soluta.
                user_id: Distinctio sequi ducimus est autem nulla.
            required:
                - id
                - user_id
                - text
                - created_at
tags:
    - name: tweets
      description: The tweets service performs operations on tweets information.
