openapi: 3.0.3
info:
    title: Tweets Service
    description: Service for managing tweets
    version: 0.0.1
servers:
    - url: http://0.0.0.0:80/api/tweets
paths:
    /api/tweets:
        delete:
            tags:
                - tweets
            summary: DeleteTweet tweets
            operationId: tweets#DeleteTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteTweetRequestBody'
                        example:
                            id: Perspiciatis laborum perspiciatis qui dolor nemo rerum.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: CreateTweet tweets
            operationId: tweets#CreateTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateTweetRequestBody'
                        example:
                            text: Ex id provident ut voluptates.
                            user_id: Voluptatem et amet.
            responses:
                "200":
                    description: Created tweet
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Tweet'
                            example:
                                created_at: "2003-07-14T09:06:41Z"
                                id: Debitis ut commodi.
                                text: Deleniti accusantium qui iure.
                                user_id: Necessitatibus dolores blanditiis incidunt hic maxime.
                "400":
                    description: 'BadRequest: Failed to create tweet'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: User was not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/tweets/like:
        delete:
            tags:
                - tweets
            summary: DeleteTweetLike tweets
            operationId: tweets#DeleteTweetLike
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: Dolorem rerum libero consequuntur perferendis et.
                            user_id: Sed quia consequuntur quidem sunt.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: LikeTweet tweets
            operationId: tweets#LikeTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: Cumque iusto deleniti.
                            user_id: Doloremque enim dolores nisi ipsam officiis.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/tweets/retweet:
        delete:
            tags:
                - tweets
            summary: DeleteRetweet tweets
            operationId: tweets#DeleteRetweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: Modi doloremque explicabo.
                            user_id: Consequatur laudantium veritatis unde.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: Retweet tweets
            operationId: tweets#Retweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: Sint qui voluptates excepturi sit quasi laboriosam.
                            user_id: Ipsa esse dolor.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - tweets
            summary: Download ./gen/http/openapi.json
            operationId: tweets#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreateTweetRequestBody:
            type: object
            properties:
                text:
                    type: string
                    example: Dolor ipsa inventore animi et et.
                user_id:
                    type: string
                    example: Sunt maiores soluta.
            example:
                text: Ipsam sunt iste quis.
                user_id: Fugit voluptatem numquam reprehenderit non accusantium.
            required:
                - user_id
                - text
        DeleteTweetRequestBody:
            type: object
            properties:
                id:
                    type: string
                    example: Enim quisquam at.
            example:
                id: Quos quia dolores perspiciatis.
            required:
                - id
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        LikeTweetRequestBody:
            type: object
            properties:
                tweet_id:
                    type: string
                    example: Veritatis deserunt rem.
                user_id:
                    type: string
                    example: Rerum voluptatem quo explicabo et laboriosam quo.
            example:
                tweet_id: Natus sed fuga corporis omnis.
                user_id: Et quae ut temporibus aperiam.
            required:
                - tweet_id
                - user_id
        Tweet:
            type: object
            properties:
                created_at:
                    type: string
                    example: "2007-06-07T12:43:33Z"
                    format: date-time
                id:
                    type: string
                    example: Magni nihil provident sunt dolorum ut.
                text:
                    type: string
                    example: Consequatur autem.
                user_id:
                    type: string
                    example: Amet ratione provident.
            example:
                created_at: "1998-04-14T08:09:22Z"
                id: Doloremque dolores et culpa.
                text: Maiores est quo dolorem libero tempore et.
                user_id: Fugiat debitis.
            required:
                - id
                - user_id
                - text
                - created_at
tags:
    - name: tweets
      description: The tweets service performs operations on tweets information.
