openapi: 3.0.3
info:
    title: Tweets Service
    description: Service for managing tweets
    version: 0.0.1
servers:
    - url: http://0.0.0.0:80/api/posts
paths:
    /api/posts:
        delete:
            tags:
                - tweets
            summary: DeleteTweet tweets
            operationId: tweets#DeleteTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteTweetRequestBody'
                        example:
                            id: b7e0a972-3700-11ef-8ce0-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: CreatePost tweets
            operationId: tweets#CreatePost
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreatePostRequestBody'
                        example:
                            text: Quaerat odit.
                            user_id: b7e08794-3700-11ef-8ce0-b2d74bfa9f65
            responses:
                "200":
                    description: Created tweet
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Tweet'
                            example:
                                created_at: "2009-03-13T12:29:33Z"
                                id: b7e091e4-3700-11ef-8ce0-b2d74bfa9f65
                                text: Illo ut eaque quo modi ad.
                                user_id: b7e092f2-3700-11ef-8ce0-b2d74bfa9f65
                "400":
                    description: 'BadRequest: Failed to create tweet'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: User was not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/posts/like:
        delete:
            tags:
                - tweets
            summary: DeleteTweetLike tweets
            operationId: tweets#DeleteTweetLike
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: b7e0d05a-3700-11ef-8ce0-b2d74bfa9f65
                            user_id: b7e0d19a-3700-11ef-8ce0-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: LikeTweet tweets
            operationId: tweets#LikeTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: b7e0c024-3700-11ef-8ce0-b2d74bfa9f65
                            user_id: b7e0c13c-3700-11ef-8ce0-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/posts/reply:
        delete:
            tags:
                - tweets
            summary: DeleteReply tweets
            operationId: tweets#DeleteReply
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteTweetRequestBody'
                        example:
                            id: b7e150ac-3700-11ef-8ce0-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: CreateReply tweets
            operationId: tweets#CreateReply
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateReplyRequestBody'
                        example:
                            text: Quo similique numquam laboriosam.
                            tweet_id: b7e1318a-3700-11ef-8ce0-b2d74bfa9f65
                            user_id: b7e132c0-3700-11ef-8ce0-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Reply'
                            example:
                                created_at: "1976-04-28T16:19:42Z"
                                id: b7e13da6-3700-11ef-8ce0-b2d74bfa9f65
                                text: Similique eveniet et sint.
                                tweet_id: b7e13edc-3700-11ef-8ce0-b2d74bfa9f65
                                user_id: b7e13ff4-3700-11ef-8ce0-b2d74bfa9f65
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/posts/retweet:
        delete:
            tags:
                - tweets
            summary: DeleteRetweet tweets
            operationId: tweets#DeleteRetweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: b7e1145c-3700-11ef-8ce0-b2d74bfa9f65
                            user_id: b7e11cae-3700-11ef-8ce0-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: Retweet tweets
            operationId: tweets#Retweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: b7e0e0f4-3700-11ef-8ce0-b2d74bfa9f65
                            user_id: b7e0e1ee-3700-11ef-8ce0-b2d74bfa9f65
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - tweets
            summary: Download ./gen/http/openapi.json
            operationId: tweets#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreatePostRequestBody:
            type: object
            properties:
                text:
                    type: string
                    example: Reprehenderit aliquam.
                user_id:
                    type: string
                    example: b7e1dc02-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
            example:
                text: Qui saepe et voluptas dicta non.
                user_id: b7e1dd06-3700-11ef-8ce0-b2d74bfa9f65
            required:
                - user_id
                - text
        CreateReplyRequestBody:
            type: object
            properties:
                text:
                    type: string
                    example: Omnis assumenda perferendis.
                tweet_id:
                    type: string
                    example: b7e1eb8e-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
                user_id:
                    type: string
                    example: b7e1ec92-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
            example:
                text: Voluptatibus consequatur.
                tweet_id: b7e1ed96-3700-11ef-8ce0-b2d74bfa9f65
                user_id: b7e1ee9a-3700-11ef-8ce0-b2d74bfa9f65
            required:
                - tweet_id
                - user_id
                - text
        DeleteTweetRequestBody:
            type: object
            properties:
                id:
                    type: string
                    example: b7e1e4c2-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
            example:
                id: b7e1e5c6-3700-11ef-8ce0-b2d74bfa9f65
            required:
                - id
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        LikeTweetRequestBody:
            type: object
            properties:
                tweet_id:
                    type: string
                    example: b7e1e706-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
                user_id:
                    type: string
                    example: b7e1e80a-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
            example:
                tweet_id: b7e1e904-3700-11ef-8ce0-b2d74bfa9f65
                user_id: b7e1e9f4-3700-11ef-8ce0-b2d74bfa9f65
            required:
                - tweet_id
                - user_id
        Reply:
            type: object
            properties:
                created_at:
                    type: string
                    example: "2001-08-26T00:01:02Z"
                    format: date-time
                id:
                    type: string
                    example: b7e1efd0-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
                text:
                    type: string
                    example: Aut omnis voluptatem suscipit modi ut natus.
                tweet_id:
                    type: string
                    example: b7e1f0d4-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
                user_id:
                    type: string
                    example: b7e1f1c4-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
            example:
                created_at: "1997-02-20T03:57:55Z"
                id: b7e1f3d6-3700-11ef-8ce0-b2d74bfa9f65
                text: Doloremque dolore ea error est omnis quibusdam.
                tweet_id: b7e1f4c6-3700-11ef-8ce0-b2d74bfa9f65
                user_id: b7e1f5ca-3700-11ef-8ce0-b2d74bfa9f65
            required:
                - id
                - tweet_id
                - user_id
                - text
                - created_at
        Tweet:
            type: object
            properties:
                created_at:
                    type: string
                    example: "1994-07-29T14:41:57Z"
                    format: date-time
                id:
                    type: string
                    example: b7e1de5a-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
                text:
                    type: string
                    example: Provident sunt est temporibus consequatur consectetur libero.
                user_id:
                    type: string
                    example: b7e1df54-3700-11ef-8ce0-b2d74bfa9f65
                    format: uuid
            example:
                created_at: "2004-07-20T04:23:50Z"
                id: b7e1e166-3700-11ef-8ce0-b2d74bfa9f65
                text: Et voluptatem aliquid eaque consequatur quibusdam qui.
                user_id: b7e1e256-3700-11ef-8ce0-b2d74bfa9f65
            required:
                - id
                - user_id
                - text
                - created_at
tags:
    - name: tweets
      description: The tweets service performs operations on tweets information.
