openapi: 3.0.3
info:
    title: Tweets Service
    description: Service for managing tweets
    version: 0.0.1
servers:
    - url: http://0.0.0.0:80/api/tweets
paths:
    /api/tweets:
        post:
            tags:
                - tweets
            summary: CreateTweet tweets
            operationId: tweets#CreateTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateTweetRequestBody'
                        example:
                            text: Voluptas omnis nesciunt incidunt et totam eos.
                            user_id: Mollitia similique corporis.
            responses:
                "200":
                    description: Created tweet
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Tweet'
                            example:
                                created_at: "1979-06-16T11:55:20Z"
                                id: Sunt sed quisquam ad corrupti labore consequatur.
                                text: Et id adipisci.
                                user_id: Quis est facere quisquam commodi totam sint.
                "400":
                    description: 'BadRequest: Failed to create tweet'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: User was not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /api/tweets/like:
        delete:
            tags:
                - tweets
            summary: DeleteTweetLike tweets
            operationId: tweets#DeleteTweetLike
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: Ducimus nobis tenetur illo iste quo.
                            user_id: Assumenda enim.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
        post:
            tags:
                - tweets
            summary: LikeTweet tweets
            operationId: tweets#LikeTweet
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/LikeTweetRequestBody'
                        example:
                            tweet_id: Nostrum labore tempore officiis explicabo id.
                            user_id: Dolores et.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - tweets
            summary: Download ./gen/http/openapi.json
            operationId: tweets#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreateTweetRequestBody:
            type: object
            properties:
                text:
                    type: string
                    example: Qui expedita laboriosam sit quibusdam.
                user_id:
                    type: string
                    example: Minus delectus.
            example:
                text: Deserunt doloremque alias eos.
                user_id: Et non delectus similique porro ullam commodi.
            required:
                - user_id
                - text
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        LikeTweetRequestBody:
            type: object
            properties:
                tweet_id:
                    type: string
                    example: Accusantium ea.
                user_id:
                    type: string
                    example: Sunt iste quis ex magni.
            example:
                tweet_id: Provident sunt dolorum.
                user_id: Voluptatem amet ratione provident et consequatur.
            required:
                - tweet_id
                - user_id
        Tweet:
            type: object
            properties:
                created_at:
                    type: string
                    example: "2003-09-11T18:18:35Z"
                    format: date-time
                id:
                    type: string
                    example: Quibusdam facere et porro vitae nisi.
                text:
                    type: string
                    example: Rem expedita iusto.
                user_id:
                    type: string
                    example: Placeat similique minima blanditiis adipisci illo et.
            example:
                created_at: "1978-07-04T04:16:54Z"
                id: Fugit magnam numquam dignissimos laborum quis.
                text: Eaque consequuntur eius sed.
                user_id: Ipsum voluptas magnam facilis alias voluptatum.
            required:
                - id
                - user_id
                - text
                - created_at
tags:
    - name: tweets
      description: The tweets service performs operations on tweets information.
