openapi: 3.0.3
info:
    title: Profile Service
    description: Service for managing users' profile
    version: "1.0"
servers:
    - url: http://localhost:80/api/profile
paths:
    /api/profile/{id}:
        get:
            tags:
                - profile
            summary: FindByID profile
            operationId: profile#FindByID
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 3083794042477558300
                    format: int64
                  example: 1464342039255902141
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
                            example:
                                bio: Quibusdam rerum rem doloribus libero.
                                username: In odit natus ut veniam eveniet inventore.
    /swagger.json:
        get:
            tags:
                - profile
            summary: Download ./gen/http/openapi.json
            operationId: profile#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        User:
            type: object
            properties:
                bio:
                    type: string
                    example: Qui et aspernatur.
                username:
                    type: string
                    example: Quis qui praesentium quo qui debitis.
            example:
                bio: Omnis enim omnis autem accusamus.
                username: Officiis ad quas nihil.
            required:
                - username
                - bio
tags:
    - name: profile
      description: The profile service performs operations on users' profile.
