swagger: "2.0"
info:
    title: Profile Service
    description: Service for managing users' profile
    version: ""
host: 0.0.0.0:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/profile/{id}:
        get:
            tags:
                - profile
            summary: FindByID profile
            operationId: profile#FindByID
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ProfileFindByIDResponseBody'
                        required:
                            - username
                            - bio
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/ProfileFindByIDNotFoundResponseBody'
            schemes:
                - http
    /api/profile/{id}/edit/username:
        post:
            tags:
                - profile
            summary: UpdateUsername profile
            operationId: profile#UpdateUsername
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
                - name: UpdateUsernameRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfileUpdateUsernameRequestBody'
                    required:
                        - username
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProfileUpdateUsernameBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/ProfileUpdateUsernameNotFoundResponseBody'
            schemes:
                - http
    /api/profile/edit/bio:
        post:
            tags:
                - profile
            summary: UpdateBio profile
            operationId: profile#UpdateBio
            parameters:
                - name: UpdateBioRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/ProfileUpdateBioRequestBody'
                    required:
                        - id
                        - bio
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/ProfileUpdateBioBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/ProfileUpdateBioNotFoundResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - profile
            summary: Download ./gen/http/openapi.json
            operationId: profile#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    ProfileFindByIDNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: FindByID_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileFindByIDResponseBody:
        title: ProfileFindByIDResponseBody
        type: object
        properties:
            bio:
                type: string
                example: Ad porro vitae recusandae.
            username:
                type: string
                example: Accusamus ipsum aut magnam.
        example:
            bio: Accusamus incidunt.
            username: Non molestiae.
        required:
            - username
            - bio
    ProfileUpdateBioBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: UpdateBio_BadRequest_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileUpdateBioNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: UpdateBio_NotFound_Response_Body result type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileUpdateBioRequestBody:
        title: ProfileUpdateBioRequestBody
        type: object
        properties:
            bio:
                type: string
                example: Laudantium velit incidunt nisi.
            id:
                type: integer
                example: 7171760185372270588
                format: int64
        example:
            bio: Et itaque.
            id: 2078907991565262692
        required:
            - id
            - bio
    ProfileUpdateUsernameBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: UpdateUsername_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileUpdateUsernameNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: UpdateUsername_NotFound_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    ProfileUpdateUsernameRequestBody:
        title: ProfileUpdateUsernameRequestBody
        type: object
        properties:
            username:
                type: string
                example: Perspiciatis velit.
        example:
            username: Occaecati nihil quae pariatur qui omnis possimus.
        required:
            - username
