swagger: "2.0"
info:
    title: Profile Service
    description: Service for managing users' profile
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/profile/{id}:
        get:
            tags:
                - profile
            summary: FindByID profile
            operationId: profile#FindByID
            parameters:
                - name: id
                  in: path
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/ProfileFindByIDResponseBody'
                        required:
                            - username
                            - bio
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - profile
            summary: Download ./gen/http/openapi.json
            operationId: profile#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    ProfileFindByIDResponseBody:
        title: ProfileFindByIDResponseBody
        type: object
        properties:
            bio:
                type: string
                example: Velit et fuga quod.
            username:
                type: string
                example: Consequatur nobis cum ut.
        example:
            bio: Omnis alias quo numquam numquam molestiae quod.
            username: Quia repellendus et ullam blanditiis natus sunt.
        required:
            - username
            - bio
