openapi: 3.0.3
info:
    title: Tweets Service
    description: Service for managing notification
    version: 0.0.1
servers:
    - url: http://0.0.0.0:80/api/notification
paths:
    /swagger.json:
        get:
            tags:
                - notification
            summary: Download ./gen/http/openapi.json
            operationId: notification#/swagger.json
            responses:
                "200":
                    description: File downloaded
components: {}
tags:
    - name: notification
      description: The notification service performs operations on notification information.
