swagger: "2.0"
info:
    title: Notification Service
    description: Service for managing notification
    version: 0.0.1
host: 0.0.0.0:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /api/notification:
        post:
            tags:
                - notification
            summary: CreateTweetNotification notification
            operationId: notification#CreateTweetNotification
            parameters:
                - name: CreateTweetNotificationRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/NotificationCreateTweetNotificationRequestBody'
                    required:
                        - tweet_id
                        - text
            responses:
                "200":
                    description: OK response.
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/NotificationCreateTweetNotificationBadRequestResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - notification
            summary: Download ./gen/http/openapi.json
            operationId: notification#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    NotificationCreateTweetNotificationBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: CreateTweetNotification_BadRequest_Response_Body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    NotificationCreateTweetNotificationRequestBody:
        title: NotificationCreateTweetNotificationRequestBody
        type: object
        properties:
            text:
                type: string
                example: Maxime sit voluptates velit.
            tweet_id:
                type: string
                example: Cupiditate minima officia dolor animi.
        example:
            text: Ullam a ut veritatis culpa.
            tweet_id: Qui amet.
        required:
            - tweet_id
            - text
