apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-app
  template:
    metadata:
      labels:
        app: notifications-app
    spec:
      containers:
        - name: notifications-app
          image: notifications_app
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: PGURL
              valueFrom:
                configMapKeyRef:
                  name: postgres-params
                  key: NOTIFICATIONS_POSTGRES_URL
          # TODO: https://github.com/okuda-seminar/Twitter-Clone/issues/350
          # - [Infra] Implement a Dockerfile for notifications service
          command: ["/bin/sh", "-c", "cd cmd/notifications && go build -o notifications . && ./notifications"]
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-app
  namespace: default
spec:
  ports:
    - port: 81
      targetPort: 80
  selector:
    app: notifications-app
