apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-postgres
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-postgres
  template:
    metadata:
      labels:
        app: notifications-postgres
    spec:
      containers:
        - name: notifications-postgres
          image: notifications_postgres:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-params
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-params
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-params
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notifications-postgres
  namespace: default
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: notifications-postgres
