apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      initContainers:
      - name: migrate-db
        image: users_app
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        env:
        - name: USERS_POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-params
              key: USERS_POSTGRES_URL
        args:
          - |
            migrate -database ${USERS_POSTGRES_URL} -path ./db/migrations up
      containers:
      - name: users-app
        image: users_service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: PGURL
          valueFrom:
            configMapKeyRef:
              name: postgres-params
              key: USERS_POSTGRES_URL
        # TODO: https://github.com/okuda-seminar/Twitter-Clone/issues/295
        # - Change health check methods
        livenessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 5
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 80
          failureThreshold: 5
          periodSeconds: 5
        
---
apiVersion: v1
kind: Service
metadata:
  name: users-app
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: users-app
