openapi: 3.1.0
info:
  title: X-Clone
  version: 1.0.0
servers:
  - url: "http://localhost:80/api"
paths:
  /users:
    $ref: ./paths/users.yml
  /users/{userId}/reposts:
    $ref: ./paths/reposts.yml
  /users/{user_id}/reposts/{post_id}:
    $ref: ./paths/delete_reposts.yml
  /users/{id}/quote_reposts:
    $ref: ./paths/quote_reposts.yml
  /users/{id}/timelines/reverse_chronological:
    $ref: ./paths/reverse_chronological_timeline_posts.yml
  /users/{id}/posts:
    $ref: ./paths/user_posts.yml
  /users/{userId}:
    $ref: ./paths/users_userId.yml
  /users/{userId}/likes:
    $ref: ./paths/users_userId_likes.yml
  /users/{userId}/likes/{postId}:
    $ref: ./paths/users_userId_likes_postId.yml
  /users/{userId}/muting:
    $ref: ./paths/users_userId_muting.yml
  /users/{sourceUserId}/muting/{targetUserId}:
    $ref: ./paths/users_sourceUserId_muting_targetUserId.yml
  /users/{userId}/blocking:
    $ref: ./paths/users_userId_blocking.yml
  /users/{sourceUserId}/blocking/{targetUserId}:
    $ref: ./paths/users_sourceUserId_blocking_targetUserId.yml
  /posts/{postId}:
    $ref: ./paths/posts_postId.yml
  /login:
    $ref: ./paths/login.yml
  /session/verify:
    $ref: ./paths/session_verify.yml
  /users/{id}/following:
    $ref: ./paths/followship.yml
  /users/{sourceUserID}/following/{targetUserID}:
    $ref: ./paths/delete_followship.yml
  /users/{userId}/followers:
    $ref: ./paths/users_userId_followers.yml
  /users/{userId}/followees:
    $ref: ./paths/users_userId_followees.yml

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    CreateUserRequest:
      $ref: ./components/requestBodies/create_user_request.yml
    CreateUserResponse:
      $ref: ./components/responses/create_user_response.yml
    CreatePostRequest:
      $ref: ./components/requestBodies/create_post_request.yml
    CreatePostResponse:
      $ref: ./components/responses/create_post_response.yml
    DeleteRepostRequest:
      $ref: ./components/requestBodies/delete_repost_request.yml
    DeleteFollowshipResponse:
      $ref: ./components/responses/delete_followship_response.yml
    GetReverseChronologicalHomeTimelineResponse:
      $ref: ./components/responses/get_reverse_chronological_home_timeline_response.yml
    GetReverseChronologicalHomeTimelineExample:
      $ref: ./components/examples/get_reverse_chronological_home_timeline_example.yml
    GetUserPostsTimelineResponse:
      $ref: ./components/responses/get_user_posts_timeline_response.yml
    FindUserByIDResponse:
      $ref: ./components/responses/find_user_by_id_response.yml
    GetFollowersByIDResponse:
      $ref: ./components/responses/get_followers_by_id_response.yml
    GetFolloweesByIDResponse:
      $ref: ./components/responses/get_followees_by_id_response.yml
