services:
  app:
    build: .
    command: yarn dev
    volumes:
      - ./twitter:/app/twitter
      - /app/twitter/node_modules
    ports:
      - 3000:3000
  api:
    build: ./twitter/api
    command: yarn start
    volumes:
      - ./twitter/api:/app
      - /app/node_modules
    ports:
      - "3002:3002"
