services:
  app:
    build: .
    command: yarn dev
    volumes:
      - ./twitter:/app/twitter
      - /app/twitter/node_modules
    ports:
      - 3000:3000
    networks:
      - x_clone
    env_file:
      - .env.local

networks:
  x_clone:
    external: true
