services:
  app:
    build: .
    command: yarn dev
    volumes:
      - ./twitter:/app/twitter
      - /app/twitter/node_modules
    ports:
      - 3000:3000
    networks:
      - x_clone
    env_file:
      - .env.local

  api:
    build: ./twitter/api
    command: yarn start
    volumes:
      - ./twitter/api:/app
      - /app/node_modules
    ports:
      - "3002:3002"
    networks:
      - x_clone

networks:
  x_clone:
    external: true
