openapi: 3.0.3
info:
    title: Notifications Service
    description: Service for managing notifications
    version: 0.0.1
servers:
    - url: http://0.0.0.0:80/api/notifications
paths:
    /api/notifications:
        post:
            tags:
                - notifications
            summary: CreateTweetNotification notifications
            operationId: notifications#CreateTweetNotification
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateTweetNotificationRequestBody'
                        example:
                            text: Rem ex cumque et quasi.
                            tweet_id: Dolorum aperiam et.
            responses:
                "200":
                    description: OK response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - notifications
            summary: Download ./gen/http/openapi.json
            operationId: notifications#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        CreateTweetNotificationRequestBody:
            type: object
            properties:
                text:
                    type: string
                    example: Enim cumque.
                tweet_id:
                    type: string
                    example: Dolores quam.
            example:
                text: Vitae ad explicabo quas est.
                tweet_id: Nam quia.
            required:
                - tweet_id
                - text
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
tags:
    - name: notifications
      description: The notifications service performs operations on notifications information.
