apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
      - name: notification-app
        image: notification_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        command: ["tail", "-f", "/dev/null"]
---
apiVersion: v1
kind: Service
metadata:
  name: notification-app
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: notification-app