apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-params
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  USERS_POSTGRES_URL: postgres://postgres:postgres@users-postgres:5432/postgres?sslmode=disable
