apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-files
  namespace: default
data:
  001_create_tables.up.sql: |
    CREATE TABLE IF NOT EXISTS tweets (
        "id" UUID PRIMARY KEY,
        "user_id" UUID NOT NULL,
        "text" VARCHAR(140) NOT NULL,
        "created_at" TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
    );
    CREATE TABLE IF NOT EXISTS likes (
        tweet_id UUID NOT NULL,
        user_id UUID NOT NULL,
        PRIMARY KEY (tweet_id, user_id),
        FOREIGN KEY (tweet_id) REFERENCES tweets(id)
    );

    CREATE TABLE IF NOT EXISTS retweets (
        tweet_id UUID NOT NULL,
        user_id UUID NOT NULL,
        PRIMARY KEY (tweet_id, user_id),
        FOREIGN KEY (tweet_id) REFERENCES tweets(id)
    );
