apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweets-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweets-app
  template:
    metadata:
      labels:
        app: tweets-app
    spec:
      initContainers:
      - name: migrate-db
        image: tweets_app:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        env:
        - name: TWEETS_POSTGRES_URL
          valueFrom:
            configMapKeyRef:
              name: postgres-params
              key: TWEETS_POSTGRES_URL
        args:
          - |
            migrate -database ${TWEETS_POSTGRES_URL} -path ./db/migrations up
      containers:
      - name: tweets-app
        image: tweets_app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        command: ["tail", "-f", "/dev/null"]
---
apiVersion: v1
kind: Service
metadata:
  name: tweets-app
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: tweets-app