import Head from "next/head";
import { Heading, Box } from "@chakra-ui/react";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box min-h-screen max-w-7xl mx-auto>
        <Heading as="h1" size="xl">
          Welcome to My Next.js App with Chakra UI!
        </Heading>
        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}

        {/* Widgets */}

        {/* Modal */}
      </Box>
    </div>
  );
}
