    // TODO: https://github.com/okuda-seminar/Twitter-Clone/issues/89 - Introduce Linter / Formatter in GitHub Actions when creating / updating PR.
    // TODO: https://github.com/okuda-seminar/Twitter-Clone/issues/93 - Introduce TS

import Head from "next/head";
import { Heading, Box } from "@chakra-ui/react";
import Sidebar from "../components/Sidebar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box min-h-screen max-w-7xl mx-auto>

        {/* Sidebar */}
        <Sidebar />
        {/* Feed */}

        {/* Widgets */}

        {/* Modal */}
      </Box>
    </div>
  );
}
