apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-deployment
spec:
  strategy:
    blueGreen:
      $patch: delete
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  replicas: 4
  revisionHistoryLimit: 4
  selector:
    matchLabels:
      app: rollouts-deployment

