apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample

bases:
  - ../../base
# resources:
#   - canary-svc.yaml
patchesStrategicMerge:
  - canary-patch.yaml
  - deployment-patch.yaml

