# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Twitter-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twitter-iOS
  pod 'TwitterProfile'
  pod 'XLPagerTabStrip'

  target 'Twitter-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Twitter-iOSUITests' do
    # Pods for testing
  end

end
