apiVersion: v1
kind: Service
metadata:
  name: rollout-blue-green-svc-preview
spec:
  selector:
    app: rollout-blue-green
  type: NodePort
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
