name: "build and deploy for tweets"
run-name: "Service: Tweets, Branch: ${{ github.ref_name }}, Env: ${{ inputs.environment }}"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Set the environment to build the container image"
        required: true
        type: choice
        options:
          - staging
          - production

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      - name: build image
        id: build-image
        uses: ./.github/actions/build_image
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          context: ./go/tweets
