name: Action for TS test
on:
  push:
    paths:
      - "ts/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ts/twitter
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: yarn
          cache-dependency-path: ./ts/twitter/yarn.lock
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run Tests
        run: yarn test
